import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import styles from "../styles/Home.module.css";

export async function getStaticProps() {
  const res = await fetch("http://localhost:3000/api/drops");
  const drops = await res.json();
  return {
    props: { drops },
  };
}

const LinkList = styled.div`
  display: flex;
  flex-direction: column;
  text-align: center;

  margin: 1rem;

  button {
    margin: 0.5rem;
    padding: 0.5rem;

    width: 20rem;
    font-size: 20px;
    font-weight: 700;
    letter-spacing: 0.2rem;

    border: none;
    border-radius: 25px;

    font-family: "Poppins", sans-serif;

    color: #444;
    background: #efefef;

    outline: none;
    cursor: pointer;

    transition: 0.2s ease-in-out;
    box-shadow: -6px -6px 14px rgba(255, 255, 255, 0.7),
      -6px -6px 10px rgba(255, 255, 255, 0.5),
      6px 6px 8px rgba(255, 255, 255, 0.075), 6px 6px 10px rgba(0, 0, 0, 0.15);
  }

  button:hover {
    box-shadow: -2px -2px 6px rgba(255, 255, 255, 0.6),
      -2px -2px 4px rgba(255, 255, 255, 0.4),
      2px 2px 2px rgba(255, 255, 255, 0.05), 2px 2px 4px rgba(0, 0, 0, 0.1);
  }

  button:active {
    box-shadow: inset -2px -2px 6px rgba(255, 255, 255, 0.7),
      inset -2px -2px 4px rgba(255, 255, 255, 0.5),
      inset 2px 2px 2px rgba(255, 255, 255, 0.075),
      inset 2px 2px 4px rgba(0, 0, 0, 0.15);
  }
`;

export default function Home({ drops }) {
  const links = drops.links;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img
          src={"/alex-reyne-logo.png"}
          alt={"Alex Reyne Profile Picture"}
          style={{ maxHeight: "10rem", marginTop: "4rem" }}
        />

        <div>
          <h1 className={styles.title}>Alexander Reyne</h1>

          <div className={styles.description}>
            <p>Software Developer @ TELUS Digital</p>
            <p>Freelance Graphic Designer</p>
          </div>
        </div>

        <LinkList>
          {links.map((link) => {
            return (
              <a href={link.url} key={link.id}>
                <button>{link.name}</button>
              </a>
            );
          })}
          <p>creativereyne@gmail.com</p>
        </LinkList>

        <footer className={styles.footer}>
          <p>
            Designed and Developed by{" "}
            <a
              href="https://github.com/alex-reyne"
              target="_blank"
              rel="noopener noreferrer"
            >
              Alexander Reyne.
            </a>
          </p>
        </footer>
      </main>
    </>
  );
}
